version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:REGION:ACCOUNT:task-definition/fargate:3"
        LoadBalancerInfo:
          ContainerName: "fargate-app"
          ContainerPort: 80
        PlatformVersion: "LATEST"
